# Generated by Terraform — do not edit directly.
Vagrant.configure("2") do |config|
  config.vm.box         = "${box_name}"
%{ if box_version != "" ~}
  config.vm.box_version = "${box_version}"
%{ endif ~}
  config.ssh.insert_key  = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "${name}" do |n|
    n.vm.hostname = "${name}"
    n.vm.network "private_network", ip: "${ip}"

    n.vm.provider "virtualbox" do |vb|
      vb.name   = "k3s-${name}"
      vb.cpus   = ${cpus}
      vb.memory = ${memory}
      vb.gui    = false
    end
  end
end
