# -*- mode: ruby -*-
# vi: set ft=ruby :
# Generated by Terraform — do not edit directly.
# Change control_plane_count / worker_count in variables.tf, then re-run terraform apply.

ENV['VAGRANT_EXPERIMENTAL'] ||= 'none_communicator'

NODES = [
%{ for node in nodes ~}
  { name: "${node.name}", ip: "${node.ip}", talos_port: ${node.talos_port}, cpus: ${node.cpus}, memory: ${node.memory} },
%{ endfor ~}
].freeze

Vagrant.configure("2") do |config|
  config.vm.box         = "theorigamicorporation/talos-virtualbox"
  config.vm.box_version = "2.0.0"
  config.vm.communicator  = "none"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  NODES.each do |node|
    config.vm.define node[:name] do |n|
      n.vm.hostname = node[:name]

      # Host-only NIC — static IP applied by Talos machine config after first boot.
      n.vm.network "private_network", ip: node[:ip]

      # NAT port-forward so talosctl can reach the maintenance API on port 50000
      # before static IPs are configured.
      n.vm.network "forwarded_port",
        guest:        50000,
        host:         node[:talos_port],
        host_ip:      "127.0.0.1",
        id:           "talos-api",
        auto_correct: false

      n.vm.provider "virtualbox" do |vb|
        vb.name   = "talos-#{node[:name]}"
        vb.cpus   = node[:cpus]
        vb.memory = node[:memory]
        vb.gui    = false

        vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
        vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
      end
    end
  end
end
