# Generated by Terraform — do not edit directly.
ENV['VAGRANT_EXPERIMENTAL'] ||= 'none_communicator'

Vagrant.configure("2") do |config|
  config.vm.box         = "${box_name}"
  config.vm.box_version = "${box_version}"
  config.vm.communicator  = "none"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "${name}" do |n|
    n.vm.network "private_network", ip: "${ip}"
    n.vm.network "forwarded_port",
      guest:        50000,
      host:         ${talos_port},
      host_ip:      "127.0.0.1",
      id:           "talos-api",
      auto_correct: false

    n.vm.provider "virtualbox" do |vb|
      vb.name   = "talos-${name}"
      vb.cpus   = ${cpus}
      vb.memory = ${memory}
      vb.gui    = false
      vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
      vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
    end
  end
end
