# -*- mode: ruby -*-
# vi: set ft=ruby :

# The "none" communicator is experimental in Vagrant 2.4.x
ENV["VAGRANT_EXPERIMENTAL"] = "none_communicator"

BOX_NAME      = "theorigamicorporation/talos-virtualbox"
BOX_VERSION   = "1.0.0"  # Talos v1.12.7

NODES = [
  { name: "cp-1",     ip: "192.168.56.10", cpus: 2, memory: 2048 },
  { name: "worker-1", ip: "192.168.56.11", cpus: 2, memory: 2048 },
  { name: "worker-2", ip: "192.168.56.12", cpus: 2, memory: 2048 },
].freeze

Vagrant.configure("2") do |config|
  config.vm.box         = BOX_NAME
  config.vm.box_version = BOX_VERSION
  config.vm.communicator = "none"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  NODES.each do |node|
    config.vm.define node[:name] do |n|
      n.vm.hostname = node[:name]
      n.vm.network "private_network", ip: node[:ip]

      n.vm.provider "virtualbox" do |vb|
        vb.name   = "talos-#{node[:name]}"
        vb.cpus   = node[:cpus]
        vb.memory = node[:memory]
        vb.gui    = false

        # Talos doesn't use a serial console but this quiets VirtualBox noise
        vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
        vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
      end
    end
  end
end
